package br.com.mesttra.opponent.entity;

import br.com.mesttra.opponent.enums.Formation;
import br.com.mesttra.opponent.enums.KeeperLevel;
import br.com.mesttra.opponent.enums.Result;
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "opponents")
public class Opponent {

    @DynamoDBHashKey(attributeName = "opponentId")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private Integer goalsConceded;

    @DynamoDBAttribute
    private Integer bestPlayer;

    @DynamoDBAttribute
    @DynamoDBTypeConvertedEnum
    private KeeperLevel keeperLevel;

    @DynamoDBAttribute
    @DynamoDBTypeConvertedEnum
    private Formation defaultFormation;

    @DynamoDBAttribute
    @DynamoDBTypeConvertedEnum
    private boolean rival;

/*    @DynamoDBAttribute
    @DateTimeFormat(iso = DateTimeFormat.ISO.DATE)
    private LocalDateTime nextMatchTime;*/

    @DynamoDBAttribute
    @DynamoDBTypeConvertedEnum
    private Result result;

}
